providerConfig:
  name: test-provider
  kind: ProviderConfig # Namespaced provider config (ProviderConfig) / Cluster scoped provider config (ClusterProviderConfig)
  secretName: test-provider-credentials

realm:
  name: test-realm
  forProvider:
    defaultSignatureAlgorithm: "RS256"
    loginWithEmailAllowed: true
    resetPasswordAllowed: true

adminUser:
  enabled: true
  username: "realm-admin"
  email: "realm-admin@pelo.tech"
  # passwordSecretRef:
  #   name: realm-admin-creds
  #   key: password

clients:
  oidc: []

roles: []

userFederation:
  ldap:
    enabled: false
    name: "ldap-user-federation"
    suffix: "$$ldap.suffix"
    forProvider:
      name: ldap
      deleteDefaultMappers: true
      editMode: "WRITABLE"
      importEnabled: true
      startTls: false
      syncRegistrations: true
      trustEmail: false
      usePasswordModifyExtendedOp: false
      useTruststoreSpi: "ONLY_FOR_LDAPS"
      validatePasswordPolicy: false
    mappers:
      userAttributeMappers: []
      hardcodedAttributeMappers: []

users: []
