apiVersion: v2
name: postgrest
icon: https://docs.postgrest.org/en/v14/_images/postgrest.png
version: 0.5.1
maintainers:
  - name: jared-prime
    email: jared.davis@pelo.tech
  - name: apkatsikas
    email: andrew.katsikas@pelo.tech
description: Helm chart for a PostgREST data api.

dependencies:
  - name: cluster
    version: 0.5.0
    repository: https://cloudnative-pg.io/charts
    condition: cluster.enabled
