apiVersion: v2
name: postgrest
icon: https://docs.postgrest.org/en/v14/_images/postgrest.png
version: 0.4.0
maintainers:
  - name: jared-prime
    email: jared.davis@pelo.tech
description: Helm chart for a PostgREST data api

dependencies:
  - name: cluster
    version: 0.5.0
    repository: https://cloudnative-pg.io/charts
    condition: cluster.enabled
  - name: ingress-nginx
    version: 4.14.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.enabled
