apiVersion: v2
name: cubejs
description: A Helm chart for Cubejs
type: application
appVersion: "0.31.6"
version: 0.1.1
keywords:
  - cubejs
maintainers:
  - email: luc.vauvillier@gmail.com
    name: Luc Vauvillier
  - email: emmanuel@pelo.tech
    name: Emmanuel Gomez
sources:
  - https://github.com/cube-js/cube.js
