apiVersion: v1
kind: Service
metadata:
  name: postgrest
  namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: postgrest
    app.kubernetes.io/instance: "{{ .Release.Namespace }}"
    app.kubernetes.io/name: postgrest
  ports:
    - name: keyserver
      port: 8000
      protocol: TCP
      targetPort: keyserver
    - name: postgrest
      port: 3000
      protocol: TCP
      targetPort: postgrest
