name: Build Docker Images
on:
  push:
    branches:
      - main
      - feat/postgrest
    tags:
      - "images/v*.*.*"

env:
  REGISTRY: ghcr.io
  REPOSITORY: pelotech/images

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        image:
          - goose
          - keyserver
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'feat/postgrest') }}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
      - uses: docker/build-push-action@v6
        id: push
        with:
          context: ./images/${{ matrix.image }}
          file: ./images/${{ matrix.image }}/Dockerfile
          push: 'true'
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
      - name: sign the published image
        env:
          TAGS: ${{ steps.metadata.outputs.tags }}
          DIGEST: ${{ steps.push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
